/**
 * Generates a .tex string matching CareerLife's canonical resume.tex template
 * (Jake/Yang based, Harshibar variant). Produces compile-ready LaTeX with the
 * same preamble, packages and custom commands as /resume.tex.
 * Data is escaped for LaTeX. Empty sections are omitted.
 */

function escapeLatex(s) {
  if (!s) return "";
  return String(s)
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/&/g, "\\&")
    .replace(/%/g, "\\%")
    .replace(/\$/g, "\\$")
    .replace(/#/g, "\\#")
    .replace(/_/g, "\\_")
    .replace(/{/g, "\\{")
    .replace(/}/g, "\\}")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}");
}

function joinOrEmpty(arr, sep = ", ") {
  return (arr || []).filter(Boolean).join(sep);
}

export function buildLatex(payload) {
  const name = escapeLatex(payload.fullName || "Your Name");
  const location = escapeLatex(payload.location);
  const headline = escapeLatex(payload.headline);
  const summary = escapeLatex(payload.summary);
  const links = (payload.links || []).filter((l) => l.url?.trim());
  const skillGroups = payload.skillGroups;
  const flatSkills = payload.skills || [];
  const projects = (payload.projects || []).filter((p) => p.title?.trim());
  const achievements = (payload.achievements || []).filter(Boolean);
  const certs = (payload.certifications || []).filter((c) => c.title?.trim());
  const education = (payload.education || []).filter((e) => e.school?.trim() || e.degree?.trim());
  const experience = (payload.experience || []).filter((e) => e.title?.trim() || e.company?.trim());

  // Header contacts: github/linkedin only (email/phone omitted by confidentiality)
  const contactParts = [];
  if (links.length) {
    for (const l of links) {
      const url = l.url.trim();
      const rawLabel = l.label || "";
      const isGithub = /github/i.test(rawLabel || url);
      const isLinkedin = /linkedin/i.test(rawLabel || url);
      const displayLabel = rawLabel || (isGithub ? "github" : isLinkedin ? "linkedin" : "link");
      const icon = isGithub ? "\\faGithub" : isLinkedin ? "\\faLinkedin" : "\\faLink";
      contactParts.push(`${icon} ${displayLabel}: \\href{${url}}{\\underline{\\bfseries ${displayLabel}}}`);
    }
  }
  if (location) contactParts.push(escapeLatex(location));
  if (headline) contactParts.push(escapeLatex(headline));
  const headerLine = contactParts.join(" \\;|\\; ");

  const skillsSection = (() => {
    if (skillGroups && Object.values(skillGroups).some((v) => v?.length)) {
      const rows = [];
      const order = [
        ["Languages", skillGroups.languages],
        ["Backend and Architecture", skillGroups.backend],
        ["Databases", skillGroups.databases],
        ["DevOps / Testing", skillGroups.devops],
        ["Tools and CI/CD Pipelines", skillGroups.tools],
        ["Core Concepts", skillGroups.concepts],
      ];
      for (const [label, items] of order) {
        if (items?.length) rows.push(`\\item \\textbf{${escapeLatex(label)}:} ${escapeLatex(joinOrEmpty(items))}`);
      }
      if (rows.length) return rows.join("\n");
    }
    if (flatSkills.length) return `\\item ${escapeLatex(joinOrEmpty(flatSkills, ", "))}`;
    return "";
  })();

  const preamble = `%-------------------------
% Resume in Latex — generated by CareerLife Builder
% Template: Jake/Yang + Harshibar variant (resume.tex)
%------------------------

\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\usepackage{fontawesome5}
\\usepackage[scale=0.90,lf]{FiraMono}
\\definecolor{light-grey}{gray}{0.83}
\\definecolor{dark-grey}{gray}{0.3}
\\definecolor{text-grey}{gray}{.08}
\\DeclareRobustCommand{\\ebseries}{\\fontseries{eb}\\selectfont}
\\DeclareTextFontCommand{\\texteb}{\\ebseries}
\\usepackage{contour}
\\usepackage[normalem]{ulem}
\\renewcommand{\\ULdepth}{1.8pt}
\\contourlength{0.8pt}
\\newcommand{\\myuline}[1]{\\uline{\\phantom{#1}}\\llap{\\contour{white}{#1}}}
\\usepackage{tgheros}
\\renewcommand*\\familydefault{\\sfdefault}
\\usepackage[T1]{fontenc}
\\pagestyle{fancy}
\\fancyhf{}
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}
\\addtolength{\\oddsidemargin}{-0.5in}
\\addtolength{\\evensidemargin}{0in}
\\addtolength{\\textwidth}{1in}
\\addtolength{\\topmargin}{-.5in}
\\addtolength{\\textheight}{1.0in}
\\urlstyle{same}
\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}
\\titleformat {\\section}{\\bfseries \\vspace{2pt} \\raggedright \\large}{}{0em}{}[\\color{light-grey} {\\titlerule[2pt]} \\vspace{-4pt}]
\\newcommand{\\resumeItem}[1]{\\item\\small{{#1 \\vspace{-1pt}}}}
\\newcommand{\\resumeSubheading}[4]{\\vspace{-1pt}\\item\\begin{tabular*}{\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}\\textbf{#1} & {\\color{dark-grey}\\small #2}\\vspace{1pt}\\\\ \\textit{#3} & {\\color{dark-grey} \\small #4}\\\\ \\end{tabular*}\\vspace{-4pt}}
\\newcommand{\\resumeProjectHeading}[2]{\\item\\begin{tabular*}{\\textwidth}{l@{\\extracolsep{\\fill}}r}#1 & {\\color{dark-grey}} \\\\ \\end{tabular*}\\vspace{-3pt}}
\\renewcommand\\labelitemii{$\\vcenter{\\hbox{\\tiny$\\bullet$}}$}
\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{0pt}}
\\color{text-grey}
\\begin{document}
\\setlength{\\parskip}{2pt}
`;

  let body = "";
  body += `\\begin{center}\n    \\textbf{\\Huge ${name}} \\\\ \\vspace{5pt}\n    \\small\n`;
  if (headerLine) body += `    \\makebox[\\linewidth][c]{${headerLine}}\n`;
  body += `\\end{center}\n\n`;

  if (summary) {
    body += `%-----------EXECUTIVE SUMMARY-----------\n\\section{EXECUTIVE SUMMARY}\n${summary}\n\n`;
  }

  if (skillsSection) {
    body += `%-----------SKILLS-----------\n\\section{SKILLS}\n\\begin{itemize}[leftmargin=0in, label={}, itemsep=3pt]\n\\small{\n${skillsSection}\n}\n\\end{itemize}\n\n`;
  }

  // Experience (senior-heavy) — before projects when present
  if (experience.length) {
    body += `%-----------EXPERIENCE-----------\n\\section{EXPERIENCE}\n\\resumeSubHeadingListStart\n`;
    for (const e of experience) {
      const bullets = (e.bullets || []).filter(Boolean);
      body += `\\resumeSubheading\n  {${escapeLatex(e.title)}}{${escapeLatex([e.start, e.end].filter(Boolean).join(" -- "))}}\n  {${escapeLatex(e.company)}}{}\n`;
      if (bullets.length) {
        body += `  \\resumeItemListStart\n`;
        for (const b of bullets) body += `    \\resumeItem{${escapeLatex(b)}}\n`;
        body += `  \\resumeItemListEnd\n`;
      }
    }
    body += `\\resumeSubHeadingListEnd\n\n`;
  }

  if (projects.length) {
    body += `%-----------PROJECTS-----------\n\\section{PROJECTS}\n\n`;
    for (const pr of projects) {
      const tech = escapeLatex(pr.tech || "");
      const gh = pr.githubUrl?.trim() ? `\\hfill \\href{${pr.githubUrl.trim()}}{\\myuline{GitHub}}` : "";
      body += `\\textbf{${escapeLatex(pr.title)}}${tech ? ` | \\textit{${tech}}` : ""}\n${gh}\n\n\\vspace{0.5pt}\n\\begin{itemize}[leftmargin=0.2in, itemsep=3pt, parsep=1pt]\n`;
      for (const b of (pr.bullets || []).filter(Boolean)) body += `\\item ${escapeLatex(b)}\n`;
      body += `\\end{itemize}\n\n\\vspace{0.1pt}\n\n`;
    }
  }

  if (achievements.length) {
    body += `%-----------ACHIEVEMENTS-----------\n\\section{ACHIEVEMENTS}\n\\vspace{0.1pt}\n\\begin{itemize}[leftmargin=0.15in, itemsep=3pt]\n\\small{\n`;
    for (const a of achievements) body += `\\item ${escapeLatex(a)}\n`;
    body += `}\n\\end{itemize}\n\n`;
  }

  if (certs.length) {
    body += `%-----------CERTIFICATIONS-----------\n\\section{CERTIFICATIONS}\n\\vspace{0.1pt}\n\\begin{itemize}[leftmargin=0.15in, itemsep=3pt]\n\\small{\n`;
    for (const c of certs) {
      const title = escapeLatex(c.title);
      const href = c.url?.trim() ? ` - \\href{${c.url.trim()}}{\\myuline{Verify}}` : "";
      body += `\\item ${title}${href}\n`;
    }
    body += `}\n\\end{itemize}\n\n`;
  }

  if (education.length) {
    body += `%-----------EDUCATION-----------\n\\vspace{-4pt}\n\\section{EDUCATION}\n\\vspace{0.1pt}\n\\resumeSubHeadingListStart\n`;
    for (const ed of education) {
      body += `\\resumeSubheading\n  {${escapeLatex(ed.school)}}{${escapeLatex(ed.year || "")}}\n  {${escapeLatex(ed.degree || "")}}{}\n`;
      if (ed.gpa) body += `    (\\textbf{GPA:} ${escapeLatex(ed.gpa)})\n`;
    }
    body += `\\resumeSubHeadingListEnd\n\n`;
  }

  body += `\\end{document}\n`;
  return preamble + body;
}

export const STAGE_STARTERS = {
  STUDENT: {
    headline: "Aspiring Developer · B.Tech Student",
    summary: "Motivated B.Tech student building fundamentals in data structures, algorithms and full-stack projects. Seeking internship opportunities to apply classroom learning to real-world problems.",
    skillGroups: {
      languages: ["Java", "Python", "JavaScript"],
      backend: ["REST APIs (basics)", "Spring Boot (learning)"],
      databases: ["MySQL"],
      devops: ["Git", "JUnit (basics)"],
      tools: ["GitHub", "VS Code"],
      concepts: ["OOP", "Data Structures"],
    },
  },
  EARLY_CAREER: {
    headline: "Backend Developer · Java + Spring Boot",
    summary: "Backend Developer with hands-on experience building REST APIs using Java and Spring Boot. Comfortable with SQL databases and backend logic through real project development and team collaboration.",
    skillGroups: {
      languages: ["Java", "Python", "JavaScript"],
      backend: ["Spring Framework", "Spring Data JPA", "Spring Boot", "RESTful APIs"],
      databases: ["MySQL", "MongoDB", "PostgreSQL"],
      devops: ["Docker", "JUnit"],
      tools: ["Git", "GitHub", "Postman", "Jenkins (basics)"],
      concepts: ["OOP", "Data Structures", "Microservices fundamentals"],
    },
  },
  SENIOR: {
    headline: "Senior Backend Engineer · Systems & Scale",
    summary: "Senior Backend Engineer focused on system design, trade-off articulation and cross-team influence. Track record driving architectural decisions under constraints and mentoring engineers to ship reliable systems at scale.",
    skillGroups: {
      languages: ["Java", "Python"],
      backend: ["Spring Boot", "System Design", "Microservices", "REST & gRPC"],
      databases: ["MySQL", "PostgreSQL", "Redis", "Kafka"],
      devops: ["Docker", "Kubernetes", "CI/CD", "Observability"],
      tools: ["Git", "Postman", "Jenkins", "Architecture Decision Records"],
      concepts: ["Distributed Systems", "Performance & Scalability", "Mentorship"],
    },
  },
};

export function applyStarter(category, existing) {
  const starter = STAGE_STARTERS[category] || STAGE_STARTERS.EARLY_CAREER;
  return {
    ...existing,
    headline: existing.headline || starter.headline,
    summary: existing.summary || starter.summary,
    skillGroups: existing.skillGroups && Object.values(existing.skillGroups).some((v) => v?.length)
      ? existing.skillGroups
      : starter.skillGroups,
  };
}
